version = 1

[install]
cmake.pkg-path = "cmake"
gnumake.pkg-path = "gnumake"
pkg-config.pkg-path = "pkg-config"
libmysqlclient.pkg-path = "libmysqlclient"
pcre.pkg-path = "pcre"
libgcrypt.pkg-path = "libgcrypt"
libevent.pkg-path = "libevent"
openssl.pkg-path = "openssl"
jemalloc.pkg-path = "jemalloc"
icu.pkg-path = "icu"
zlib.pkg-path = "zlib"
bison.pkg-path = "bison"

[build]
fluffos.sandbox = "pure"
fluffos.command = '''
export CMAKE_PREFIX_PATH="$FLOX_ENV"

rm -rf build
mkdir -p build && cd build

cmake \
  -DMYSQL_INCLUDE_DIR=$FLOX_ENV/include/mysql \
  -DCMAKE_INSTALL_PREFIX="$out" \
  ..

make -j$(nproc)
make install
'''
